image: node:16.5.0
pages:
  variables:
    # PUBLIC_URL: /compose-sdk-react-demo
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
      prefix: yarn
    paths:
      - node_modules/
  script:
    - yarn config set npmAuthToken ${GITHUB_PACKAGE_REGISTRY_AUTH_TOKEN}
    - yarn
    - yarn build:dirty
    - cp dist/index.html dist/404.html
    - cp -a dist/. public/

    # Deployment to S3
    - apt-get update && apt-get install -y awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync public/ s3://compose-sdk-public-demo --delete

  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"'
      when: manual
      allow_failure: false
